### ISSUE TITLE
Swift WASM+WASI does not work

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#2] opened 2020-10-22 20:35 UTC
Modules built from swift-wasm do not execute. The error is: `Err(Exited with i32 exit status 71)`

Example Hello World code:

```swift
print("content-type: text/plain\n\n");
print("Hello WAGI!\n");    
```

**Comment by radu-matei** [comment] 2020-11-14 02:05
I just built a module with SwiftWasm 5.3.0, ran it through `wasm-opt -O` (default optimization) and executed it WAGI - everything just worked on Linux, so I would assume that's a macOS specific issue maybe?

```
$ swiftc --version
SwiftWasm Swift version 5.3 (swiftlang-5.3.0)
Target: x86_64-unknown-linux-gnu
```

**Comment by radu-matei** [comment] 2021-02-03 18:20
I think we can safely close this issue, as we have built multiple Swift Wasm modules that seem to run fine with WAGI.

Feel free to reopen if the issue is still present.

**Closed by radu-matei** 2021-02-03 18:20 UTC
